version: '3'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

volumes:
  db_data: